### ISSUE TITLE
In the cycling map, show "Natural Woods" in green 

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#101]
and preferably with little tree icons like the screen capture from OSM
Note: Its marked hiking map. Just plain green.
Location example: https://israelhiking.osm.org.il/map/18.20/32.1807/34.8365

![image](https://user-images.githubusercontent.com/49042192/122634597-c10fe800-d0e7-11eb-8df1-56c069e73065.png)

![image](https://user-images.githubusercontent.com/49042192/122634641-f1f01d00-d0e7-11eb-90f4-3bc71f577e4c.png)

**Comment by valleyofdawn** [comment]
Natural woods are shown in green with trees.
In this case someone called "Velocity club" (ahm ahm) tagged the entire municipal area of Herzlia as "residential area" which rode on top of the woods and farming areas and turned them grey.
I undid that.  "Residential area" should be reserved to built up areas with homes, as municipal boundaries often include industrial and agricultural areas etc.
I'll also place residential areas lower in the drawing hierarchy to be on the safe side.

**Comment by Tsurha** [comment]
<div dir="rtl">
תודה רבה גיא!

אגב שדה התעופה הרצליה מופיע במפת האופניים רק בזום 13
ואז יש עומס מידע טקסטואלי על העיר עצמה.
אם ההחלטה של 13 היא בשביל שדות התעופה הגדולים אז מובן.
בכל מקרה הייתי מציג את השם גם מזום 14 ומעלה.
בכזו התמקדות לא תהייה בעייה של עומס

**Comment by Tsurha** [comment]
גיא אחרי השינויים הללו עכשיו הרצליה ללא צבע עירוני

![image](https://user-images.githubusercontent.com/49042192/122688674-67620780-d226-11eb-90a9-be6d1f27a5b5.png)

**Comment by valleyofdawn** [comment]
אז צריך לסמן את גבולות השטח הבנוי
תוודא שהפוליגון לא שם עם תיוג לא נכון
