### ISSUE TITLE
Present "Wetland"

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#107]
A request to show "Wetland" areas.  For example here:
https://www.openstreetmap.org/edit#map=17/32.24464/34.85986

Currently not shown in either hiking or biking.
Thank you.

P.S.  a "Pond" is shown very well. 

![image](https://user-images.githubusercontent.com/49042192/122666010-86738180-d1b3-11eb-8689-66c5cc7254f1.png)

**Comment by valleyofdawn** [comment]
It was already in the map but, in this particular case, covered by some farmland. moved it up the drawing hierarchy.
