### ISSUE TITLE
Reduce size of restaurant names in cycling map

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#108]
Example:  A specific restaurant gets all the attention in Tel Mond...  This one is here: https://israelhiking.osm.org.il/map/17.58/32.2531/34.9191

Seems inappropriate. Its either too big or superfluous.  For your consideration.

![image](https://user-images.githubusercontent.com/49042192/122667967-672e2180-d1be-11eb-9974-6b9ddb4ed948.png)

**Comment by HarelM** [comment]
I disagree. See the issue I opened here: #94...
If there's anything interesting in Tel Mond it's probably this restaurant...

**Comment by Tsurha** [comment]
בזום הספציפי של צילום המסך ממליץ שיראו את שם היישוב. 

בזום יותר גבוה אם תהיה מסעדה, זה כבר סביר

**Comment by Tsurha** [comment]
דוגמה נוספת לכך שצריך להקטין את גודל פונט המסעדות. הפעם מאזור התעשיה רעננה (קריית אתגרים) ורק לגבי מפת האופניים. 
שם האיזור מוצג בפונט קטן יותר מאשר המסעדות וצריך להיות הפוך או לפחות גודל זהה.
הטקסט מסעדת קיוטו מכסה 3 בניינים נפרדים ליד הבניין שבו היא נמצאת.
כאשר עוברים לזום אחר מופיעות מסעדות אחרות. זה תקין עקב כמות הטקסט שאפשר להציג בלי ערבוב אבל מדגיש את האירוניה של למה להציג מסעדה אקראית עם פונט ענק. 
ולבסוף כרפרנס לדיון על מתחמים: בתוך מתחם הקאנטרי קלאב כתוב רק בריכת פעוטות במקום קאנטרי קלאב

![image](https://user-images.githubusercontent.com/49042192/127447790-8f7225ed-e591-430d-9721-dfa67673d373.png)

![image](https://user-images.githubusercontent.com/49042192/127448153-9a5f61f7-989e-4aad-b13f-cafe7b57d3f6.png)

**Comment by zstadler** [comment]
I'd like to suggest that:
- Minimal zoom for restaurant should remain as is
- Restaurant font size should be the same as street names
- At the minimal zoom level only the icon will be shown. The name will be added in the next zoom level

@Tsurha and @HarelM, what do you think?

**Comment by HarelM** [comment]
Sounds like a good solution to me.
Would be nice to see how the above examples would look after the change, if possible.

**Comment by Tsurha** [comment]
Should be good.

**Comment by zstadler** [comment]
> Sounds like a good solution to me. Would be nice to see how the above examples would look after the change, if possible.

#### Tel Mond example
Zoom 16 - first appearance of the icon
![image](https://user-images.githubusercontent.com/1304610/210612980-2b409b7e-b730-4042-a79b-12b5418d0d8c.png)

Zoom 17 - name is added
![image](https://user-images.githubusercontent.com/1304610/210613206-346c031b-93bc-44ba-bef7-c5acf01aa3c7.png)

#### Ra'anana example
At zoom 16.8
![image](https://user-images.githubusercontent.com/1304610/210614784-e20fe95a-0a1a-49cd-b133-2c2589270a0d.png)

At zoom 17.8
![image](https://user-images.githubusercontent.com/1304610/210615181-3abe26c9-33c5-4193-9d9a-95f87fca6cec.png)

**Comment by HarelM** [comment]
LGTM, Thanks!
