### ISSUE TITLE
Present name of area which is an amenity=university

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#109]
A point would solve the need for areas. Its the same convention as done for a village or city with a point. 
Check for example Hakfar Hayarok Or TAU.
All the details in them are presented but what are all these? Currently unknown 

![image](https://user-images.githubusercontent.com/49042192/122668491-f805fc80-d1c0-11eb-9f60-aa01ea0b77ed.png)

![image](https://user-images.githubusercontent.com/49042192/122668599-81b5ca00-d1c1-11eb-8d38-791ee44f48e5.png)

**Comment by zstadler** [comment]
This issue is a duplicate of #90, which is a duplicate of #65, which is a duplicate of #64.

@Tsurha, Please search the existing issues before opening a new one.

**Comment by Tsurha** [comment]
<div dir="rtl">
היי זאב
זה לא אותו דבר
כרגע ההצעה שלי היא שלא להשתמש באיזור אלא להשתמש בנקודה.
את האיזור הראל הסביר לי שלא יכול היה לממש כי מסובך טכנית.  נקודה זה קל יותר בדיוק כמו שכותבים את שם העיר או המושב.

**Comment by zstadler** [comment]
<div dir="rtl">

[התשובה שלי לגבי מפת הטיולים](https://github.com/IsraelHikingMap/VectorMap/issues/65#issuecomment-720422162) kt vh,v קשורה לשאלה טכנית כזו או אחרת.

אני לא מכיר את ההסבר של הראל. אתה מוזמן להגיב בקריאה שבה ההסבר ניתן.
</div>

**Comment by Tsurha** [comment]
@valleyofdawn - for your consideration in @ILMTB .
The request is to facilitate general orientation and is reduced to adding just the name of amenity=university and just when there is a OSM point.  Once done and I can check, I'll add the main universities in Israel.

**Comment by zstadler** [comment]
@valleyofdawn,

- The `college` class in the `poi` layer already includes universities and colleges
- I think there are far more universities/collages mapped that you assume. I suggest you examine the impact on the map readability.

**Comment by valleyofdawn** [comment]
Colleges are out.
There are missing universities and mistagged buildings In Hadassa Ein-Karem. See here:
http://overpass-turbo.eu/s/18Dg
There's also an inflation of institutes in the west bank, but I can live with that.
If @Tsurha cleans the mess according to the guidelines here: https://wiki.openstreetmap.org/wiki/Tag:amenity=university
I'll add the universities.

**Comment by Tsurha** [comment]
<div dir="rtl">
התייעצות: 
 אולי הנכון הוא לחזור לכתוב את השם לפי פוליגון ולא נקודה. ככה זה יצמצם רק לקמפוס שאנחנו רוצים שיוצג לצורך התמצאות

@valleyofdawn

**Comment by valleyofdawn** [comment]
זה יוריד אותך ל-40, לא כולל השטחים.
לדעתי הפתרון הכי טוב הוא להגדיר relation לכל קמפוס משמעותי ולהראות רק אותם - רמת אביב, הר הצופים, גבעת רם, הטכניון וכו'.
צריך לוודא ש @zstadler יכול להוסיף כזה relation לסכימה.

**Comment by valleyofdawn** [comment]
Also then you can add back large college campuses, such as the college of management at Rishon Le-Zion etc.
