### ISSUE TITLE
Discussion about the icon for hospitals and clinics in Palestinian areas

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#118]
Any ideas?

The current state in ILMTB is awkward with a Magen David in Palestinian area:
![image](https://user-images.githubusercontent.com/49042192/126031293-4bd7ee89-48b9-44d7-9815-75377f577d88.png)

An international symbol exists but it would be awkward in Israel
![image](https://user-images.githubusercontent.com/49042192/126031416-0d225337-6cf8-48d9-be2d-07c0e9db83f5.png)

**Comment by zstadler** [comment]
My conclusion, based in a long discussion on Facebook, is that there is no international sign for first-aid/clinic/hospital.

Therefor, I don't see any reasonable way to address this issue and I prefer to close it.

**Comment by Tsurha** [comment]
I hope there will be no need to go into any medical clinic anywhere, regardless of how is it marked on the map...
