### ISSUE TITLE
Show emergency=defibrillator

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#120]
<div dir="rtl">
עם העליה במודעות לצורך בדיפיברילייטור לצורך הצלה ממצבי דום לב, מציע להציג אותם על המפה.  צריך כמובן להחליט מאיזה זום והלאה.

אנו שומעים יותר על מקרים שבהם האירוע מתרחש כחלק מאירוע ספורט בו הלב דוחף כמויות דם גדולות וסתימת עורקים עלולה להביא אותו לפרפור חדרים. לכן עבור אופניים זה במיוחד רלוונטי.
הוספתי אחד כדוגמא: https://www.openstreetmap.org/edit#map=19/32.19426/34.84707

ניתן להעתיק מידע ציבורי בהמשך מ: https://defi.co.il/#/map

**Comment by HarelM** [comment]
אני לא חושב שצריך.
יש אפליקציה יעודית לכך, עם יכולות ניווט לדביברילטור הקרוב.
אני לא מוצא סיבה טובה להוסיף את זה.
אתה מוזמן ליצור שכבה פרטית מהמידע בדומה למידע על הגבים...

**Comment by zstadler** [comment]
בנוסף למה שהראל כתב, הגישה שלנו היא להתרכז במה שחשוב למטיילים, עם דגש מובהק על טיול בטבע

**Comment by Tsurha** [comment]
מבין ומקבל. 
ממילא ההתרכזות שלי היא ברוכבי אופניים ויש לכם רפרנט מעולה לעניין. שיראה מה הוא חושב רק עבור 
@ILMTB
או איך שמתייגים את האופניים

**Comment by Tsurha** [comment]
Recommendation: Zoom 15 and higher
