### ISSUE TITLE
In MTB, Zoom>=17 , show one way arrows

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#121]
Helps when planning a city cycling route 
@valleyofdawn

**Comment by Tsurha** [comment]
This is still relevant for planning an urban cycle

![image](https://user-images.githubusercontent.com/49042192/205431510-0f0d22a9-e6e0-42e0-94e2-38daf56ffe18.png)

**Comment by zstadler** [comment]
@Tsurha,

Currently direction arrows are shown on mixed-use paths and bike-only paths.
Do you think it should be on any road, including motorways like HWY6? I'm not so sure.

**Comment by Tsurha** [comment]
Hi Zeev, 
The request is in order to help plan a cycling route in the city. So its only from zoom 17 and higher.  
I do not mind if its shows or not shows on highways. I do not think it will bother anyone this way or that way in this high zoom.  I would do whatever is easy to implement.  

Another note: I would not show anything if its not a one way.
Thank you for looking into it!

**Comment by Tsurha** [comment]
Looks good!
