### ISSUE TITLE
Decrease visibility/emphasis of walls and fences in low zoom levels?

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#122]
I'm not sure how this is looking for outdoors, or other places, it's worth comparing, but I get the feeling that walls and fences (but mostly walls) are a bit strong in low zoom levels.
Check out the below screenshot (just below the 'ח' of Haifa).
You can see around haifa bay that walls are strong (for me it feels a bit too strong as you can't see building in this zoom level), a fence is also there and I'm not sure it's too strong, but worth looking into as well while looking into this issue.
![image](https://user-images.githubusercontent.com/3269297/132058034-e4241369-3d9d-4c64-9997-cc49667861a7.png)

I don't see this issue in the ILMTB map as the minimal zoom level for walls and fences there is lower I believe.

**Comment by zstadler** [comment]
This is a result of the  desire to show the separation wall in zoom 12 and above.

![image](https://user-images.githubusercontent.com/1304610/132087230-15c47378-a29a-43c1-8709-e21608dfbb4c.png)
