### ISSUE TITLE
Do not present underground buildings

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#123]
This underground water reservoir is mapped in layer -3
https://israelhiking.osm.org.il/map/17.61/32.1930/34.8305

I don't think it should show this way, if at all

![image](https://user-images.githubusercontent.com/49042192/132091308-6d69208e-a3ad-431a-ae8d-593ec5037de3.png)

![image](https://user-images.githubusercontent.com/49042192/132091322-84926fa2-12c7-44fa-bafe-fa5da94878ce.png)

**Comment by zstadler** [comment]
Pending https://github.com/openmaptiles/openmaptiles/pull/1241

This would also require correcting the tagging of underground buildings to use the `location=underground` tag, as [described in the wiki](https://wiki.openstreetmap.org/wiki/Buildings#Mentionable_usage).

**Comment by zstadler** [comment]
@Tsurha,
Please add the `location=underground` tag where appropriate.
