### ISSUE TITLE
Observation towers do not appear on hiking map

### ISSUE THREAD

**Issue by nonZero** [IsraelHikingMap/VectorMap#126]
Example Node:
https://www.openstreetmap.org/node/1305525482
(Includes an image)
https://israelhiking.osm.org.il/map/16.89/31.8421/35.0071
(Appears on biking map)

Overpass Turbo query:
https://overpass-turbo.eu/s/1bIY

https://wiki.openstreetmap.org/wiki/Tag:tower:type%3Dobservation

**Comment by zstadler** [comment]
It was a design decision to exclude the observation towers from the hiking map. The map shows observation towers that serve as viewpoints.

The designer of the biking map has chosen differently, as is the case for other map elements, such as bike shops.
