### ISSUE TITLE
Show gates that are lines (not just points)

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#129]
I have added a gate as point and got an OSM remark that it should be a line.  Added a gate as a line as well but that is not reflected in IHM.  All here: https://israelhiking.osm.org.il/map/22.00/32.3005/34.8939

I'll be delete the gate point once the map reflects the line too.

**Comment by zstadler** [comment]
Our map, as well as the standard OSM map do not support linear gates.
![image](https://user-images.githubusercontent.com/1304610/144989131-36834721-c3f4-4e28-a334-6cb6b8d1e79c.png) ![image](https://user-images.githubusercontent.com/1304610/144989033-f32a98ca-f0dc-496a-8413-3b6ff2defad0.png)

**Comment by Tsurha** [comment]
Their editor suggests it should be a line...


![image](https://user-images.githubusercontent.com/49042192/144997302-6e502016-6197-4e2c-93a8-3bcf37564789.png)

**Comment by zstadler** [comment]
[Access control on highways (e.g. for blocking a path or road)](https://wiki.openstreetmap.org/wiki/Key:barrier#Access_control_on_highways_.28e.g._for_blocking_a_path_or_road.29) should be placed on the highway it controls.

 See [How to map barrier nodes](https://wiki.openstreetmap.org/wiki/Key:barrier#How_to_map_barrier_nodes) and [the correction for the above mapping](https://www.openstreetmap.org/edit?node=9317084006#map=19/32.30053/34.89392):

![image](https://user-images.githubusercontent.com/1304610/145017883-3c4ef729-8858-4142-b4ea-add9a584998b.png)
