### ISSUE TITLE
Add yellow background in Yafia to MTB map

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#139]
Yafia Singletrack: https://israelhiking.osm.org.il/poi/OSM/relation_14905588?language=he
 is supposed to have a yellow background in the MTB map, just like its brother Kfar Hachoresh. It does not.
  
![image](https://user-images.githubusercontent.com/49042192/206863452-df2137f2-b1bb-45a2-97ee-c643976ca62a.png)

**Comment by zstadler** [comment]
Please use `colour=yellow` rather than `Yellow`

**Comment by Tsurha** [comment]
Looks good. Thank you!
