### ISSUE TITLE
Do not show one way arrows on invisible / construction roads

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#143]
When a road is in construction and not presented, rather not show its one way arrows.
Have a look here: https://israelhiking.osm.org.il/map/17.14/32.2116/34.8290

![image](https://user-images.githubusercontent.com/49042192/216833321-f70b4678-1202-4250-9794-ea54e5f29f50.png)

**Comment by zstadler** [comment]
Similarly, check tunnel and bridges

**Comment by Tsurha** [comment]
Do you mean that you'd like a checking done if the tunnel and bridges mapping is correct?  I did not map it and am not sure where is the exact info comes from. However, a road is being built there. So it may actually be fine.

**Comment by zstadler** [comment]
It was a note to myself, as the screenshot shows the casing of a tunnel that does not exist yet.
![image](https://user-images.githubusercontent.com/1304610/217032204-66862563-96f2-4fc1-9469-c431dca2b972.png)

**Comment by Tsurha** [comment]
Note that this is still a bug in MTB map
For example here: https://israelhiking.osm.org.il/map/18.31/32.2042/34.8441

![image](https://user-images.githubusercontent.com/49042192/225412344-db12d15f-d827-43ac-be8f-7b4d761c6858.png)
