### ISSUE TITLE
In cycling map, do not show non existing cycling lanes around paths

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#148]
For example here:
https://israelhiking.osm.org.il/map/18.65/32.1168/34.8258

Cycling is allowed there, but there are no real cycling lanes.

![image](https://user-images.githubusercontent.com/49042192/230716246-a19d1578-a41c-41a4-b84c-578fee321651.png)

**Comment by zstadler** [comment]
I'm confused. I thought that `cycleway=track` means that there is a cycling lane.
For example, https://www.openstreetmap.org/way/174274992

**Comment by Tsurha** [comment]
**Seems like at the above point we have two issues:**
a) the tagging is wrong in OSM (as there are no cycling path on either side of Pinhas Rosen there.
b) the rendering to IHM cycling is wrong.  It shows a cycling lane to both the left and the right of that Path.  The result is 4 cycling lanes around Pinhas Rosen...




**Here is a different rendering issue example:**
https://israelhiking.osm.org.il/map/19.02/32.0987/34.7830
At the 2 points I circled, a lane exists but the map shows 3 cycling lanes in each. Instead of just the middle one, two are added to its right and left.  
![image](https://user-images.githubusercontent.com/49042192/230739742-a2428846-f222-47e6-9c9f-2b7f55f60df0.png)

**Comment by zstadler** [comment]
There are two topics that need to be considered separately:

1. Is the OSM tagging appropriate for the facts on the ground?
2. What is the appropriate rendering of a the OSM tagging?

In [Add support for cycle lanes and tracks via the cycleway key #61](https://github.com/IsraelHikingMap/VectorMap/issues/61#issuecomment-1371006284) @nonZero wrote:
> Regarding rendering: For cycling maps the whole road/way could be rendered as "cycling friendly", while ignoring the left/right rendering.

In all cases presented in this issue, the ways were tagged with `cycleway=track` and rendered according to the above. If there needs to be a change/refinement of this request, please agree on a new requirement.

**Comment by Tsurha** [comment]
I started fixing OSM tags in the above cases.  Waiting to see the new IHM rendering but that takes long or may be off right now. 

I also see that the ID editor recommends to remove the  cycleway=track tag when its together with highway=cycleway.  I'm waiting to see if it solves the 3 lines near Even Gvirol 

![removal of cycleway track suggested](https://user-images.githubusercontent.com/49042192/230764696-5f6820d0-aa41-4e07-a190-42a75b9eef66.PNG)

**Comment by Tsurha** [comment]
Where I fixed manually, the three lines are thankfully gone.  

However there are more I saw by just browsing and probable many more I didn't see.  A few examples: 
https://israelhiking.osm.org.il/map/20.58/32.0800/34.7843
https://israelhiking.osm.org.il/map/21.29/32.0593/34.7791
https://israelhiking.osm.org.il/map/21.29/32.0586/34.7785
https://israelhiking.osm.org.il/map/21.24/32.1005/34.7973

Could you not render additional cycling lines to the right and left of highway= cycleway, footway, pedestrian, path... ? Alternatively find all of them in Israel to see if it better to manually fix?

Personally after the above-mentioned #61 fix I'm less confident a cycling path exists around all the roads that it is attached to, besides in Modi'in :-)

**Comment by zstadler** [comment]
In general, tagging errors should be fixed at the source rather than hidden by the renderer.

[This query](https://overpass-turbo.eu/s/1tyh) finds all `highway=cycleway/footway/pedestrian/path` with `cycleway=track` in Israel. There are 27 of them, all but 3 are in the Tel-Aviv area. 

![image](https://user-images.githubusercontent.com/1304610/230846628-36e5fd50-48cc-4921-89b8-f2c9b8ad32c9.png)

It would be best to check the facts on the ground and correct the tagging where needed.

**Comment by Tsurha** [comment]
Thank you for the query.  I fixed all those instances so now just one cycling path is presented.  
Apparently I should have also specified cycleway=lane and the above four.  So used your query with that too.  
For now I think this is it.

**Comment by zstadler** [comment]
Excellent!
If this issue is no longer applicable, please close it.
