### ISSUE TITLE
Text and icon do not keep the same position when rotating

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#150]
## Problem
the icon and the text are not rotated "together".
See the following image - סאלחה and I think also מצפה איילת.
![image](https://user-images.githubusercontent.com/3269297/232252489-dfd7240a-97d3-4440-ba8e-3a5ce35d12ec.png)
This is the location:
https://israelhiking.osm.org.il/map/17.28/33.0757/35.4523
You'll need to rotate the map so that when south is up.

When north is up everything looks as expected:
![image](https://user-images.githubusercontent.com/3269297/232252559-88852646-60e1-47f9-ac77-979f56ab4ee1.png)

**Comment by zstadler** [comment]
This looks like a Maplibre issue.

The style uses

https://github.com/IsraelHikingMap/VectorMap/blob/b5e0ab6d9400aff6aa333f864dc0ef189261b9e3/Styles/IHM.json#L4831

yet the text shifts left and right when rotating the map

![image](https://user-images.githubusercontent.com/1304610/232253085-b865da20-ce0a-4b6a-9416-c98bcb3a6cfe.png)
![image](https://user-images.githubusercontent.com/1304610/232253090-0fdd08be-34bb-4818-acdb-040414b200d8.png)

There is also an up-and-down movement in-between
![image](https://user-images.githubusercontent.com/1304610/232253239-61767d51-805b-4bd8-b1af-c6575d2a0fe6.png)
![image](https://user-images.githubusercontent.com/1304610/232253262-7e959827-d930-4358-b281-c670adea476f.png)

**Comment by HarelM** [comment]
While I'm not arguing this might be a maplibre bug, can you think why the ruins and viewpoint texts behaves differently (one overlaps while the other moves away from the icon)?
I'll see if I can create a minimal reproduction using only maplibre and open a bug there if I succeed...

**Comment by zstadler** [comment]
It also happens with ruins

![image](https://user-images.githubusercontent.com/1304610/232253851-84918179-6eb9-42c8-af87-58ae6775bfc9.png)
![image](https://user-images.githubusercontent.com/1304610/232253860-e41a3aa0-f1f1-40b7-8481-301ca43fead0.png)

BUT, it is not a Maplibre bug!

If `text-translate` is used to shift the text relative to the point, `"text-translate-anchor": "viewport"` should also be used. I have no idea why this is not the default.

On the other hand, I have no idea why I used `text-translate` in the first place. `text-offset` does the work on its own.
