### ISSUE TITLE
Street names are hard to read

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#152]
In continue to our conversation, the following is the issue:
It's a bit hard to read the street names due to two factors:
1. They are a bit small
2. The street lines are creating dashes that are "confusing to the eye".

Here's an example: https://israelhiking.osm.org.il/map/18.83/33.0859/35.1147
![image](https://github.com/IsraelHikingMap/VectorMap/assets/3269297/c4380f8c-00a9-4d6c-8849-6f5d6b7ed89c)

**Comment by zstadler** [comment]
Is this better:

![image](https://github.com/IsraelHikingMap/VectorMap/assets/1304610/c93778ba-ce22-497c-a2b0-b8e7d356c64b)

**Comment by HarelM** [comment]
Yes, although the דרך in the דרך המייסדים is still a bit confusing, nevertheless, the improvement is noticeable.

**Comment by HarelM** [comment]
It might be that I need to get used to the new change, but I think the following places names looks worse than what it used to look, I liked the old version better (check out the right side of the following image).
![image](https://github.com/IsraelHikingMap/VectorMap/assets/3269297/591a76f7-b555-482a-95c3-b3c289abb1cd)

**Comment by HarelM** [comment]
I tend to say that this improvement should only be applied to street names due to how this are placed (with the street lines and all), other labels are less affected by this issue and I think look better in the old version.
Street names do appear more readable to me now, thanks!!

**Comment by zstadler** [comment]
@HarelM, 
You may play with [the above IHM.json](https://raw.githubusercontent.com/IsraelHikingMap/VectorMap/154246032ca3d38d2defa07e464c9f5475e4d401/Styles/IHM.json)

**Comment by HarelM** [comment]
Looks great!
I think the size can increase for larger zooms for when the street width gets bigger, but it's better than now, no question.
The following is the max zoom on mobile:
![Screenshot_20230804_184655_Israel Hiking Map](https://github.com/IsraelHikingMap/VectorMap/assets/3269297/540d77d6-6d16-4e66-9b06-f0b4ad4eea81)

**Comment by zstadler** [comment]
I tend to think that
- The current font size makes the names readable in all zoom levels.
- When the user zooms-in, it is probably in order to improve the visibility of other elements of the map, not the names.
- Further increasing the font in high zoom level could reduce the visibility of the other elements.

**Comment by HarelM** [comment]
Much like the roads getting bigger and creating the intuitive feeling that you are zooming in and help with the orientation, I believe the text size should follow the same pattern, it's less about readability and more in the "feeling" area of things. My two cents I guess. #15, #77
Regardless of the above, I believe this solution is better than current and should be merged.
