### ISSUE TITLE
Show railway=unused on map

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/VectorMap#157]
מסילת הרכבת של נחל שורק לא מופיעה במפה כי היא מתויגת railway=unused.
למרות שהיא לא פעילה היא מגודרת ורלוונטית מאוד למטיילים. כדאי לשנות את הכלל כדי שהיא תופיע.

**Comment by zstadler** [comment]
האם לדעתך צריך להיות הבדל ויזואלי בין מסילה בשימוש לבין מסילה שאינה בשימוש?
מה בדבר [סטטוסים אחרים של חוסר שימוש](https://wiki.openstreetmap.org/wiki/Demolished_Railway)?

אלו הם [הקטעים המתוייגים עם railway=disused](https://overpass-turbo.eu/?Q=way%0A++%5Brailway%3Ddisused%5D%0A++%28area%3A3606195356%29%3B%0Aout+meta+geom%3B&C=31.830557%3B35.104065%3B8&R=) בישראל.

**Comment by amiad** [comment]
בתור מטייל לא אכפת לי אם המסילה בשימוש, חשוב שהיא בשטח.
אם היא ממש הרוסה (abandoned וכאלה) אולי כבר אין צורך להציג. אבל כנראה שאין צורך להסתבך ויהיה בסדר להציג את כל railway=* אותו דבר.

**Comment by zstadler** [comment]
לפעמים ממסילת הרכבת נשארה רק התלולית, כמו ברכבת העמק ולכיוון צמח או באיזור ניצנה, כך שלהציג במפה "מסילת רכבת" שם זה נראה לי כמה צעד רחוק מדי. ולכן אני אל חושב שיש מקום להציג מסילות שהדרדרו מתחת לרמת disused.
אם אני זוכר נכון, בחלק מה disused בישראל אין יותר מסילות ושאר התשתית המצדיקות את הסטטוס הזה. למשל, גשרי הרכבת של הרכבת הטורקית והמנדטורית בנגב, לצידי כביש 6, פארק המסילה בדרום תל אביב ועוד.

**Comment by amiad** [comment]
נכון, אז יהיה כדאי להציג רק disused. אם אין מסילה פשוט צריך לתקן את התיוג, לא את רנדור המפה.
נראה  שחוץ מהמסילה של נחל שורק כמעט כל disused מסמנים מקטעים לא בשימוש ליד תחנות רכבת.

**Comment by zstadler** [comment]
יש כאן שאלה בסיסית יותר: מה הקריטריון לתיוג של מסילת ברזל כ"מסילה שאינה בשימוש - railway=disused".

הוויקי של OSM אומר:
This tag is used to tag evidence of lack of maintenance. If the top of the rail or rail head is not visible use railway=disused
הההגדרה הזו תואמת את הגישה הכללית של OSM שבה התיוג נקבע על ידי העובדות בשטח.

לכן, להבנתי, אין מקום לתיוג של המסילה מבית שמש למלחה, דרך נחל שורק, כ railway=disused. המסילה שמישה לחלוטין וכמו שציין [יואב רופא](https://www.facebook.com/groups/994960670559126/user/594409560/), מתבצעות בה נסיעות תחזוקה.

מקורות:
[https://wiki.openstreetmap.org/wiki/Railways#Life-cycle](https://wiki.openstreetmap.org/wiki/Railways#Life-cycle)
[https://wiki.openstreetmap.org/wiki/Demolished_railways](https://wiki.openstreetmap.org/wiki/Demolished_railways)
