### ISSUE TITLE
Default name for non existing Hebrew tag

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#21]
The following point is written in English on the map while presented in Hebrew in the POI:
https://israelhiking.osm.org.il/poi/OSM/node_1282821195?language=he
I'm guessing that this is due to a missing `name:he` tag.
I think that the raster map used to be able to address this, right?
In any case I think a bulk update of entities that do not have `name:he` but their `name` is in Hebrew can fix this issue, but won't prevent future problems.
Nevertheless the bulk update is correct and wanted in terms of OSM I believe...
Didn't swiftfast created a script to do it?

**Comment by zstadler** [comment]
In Maperitive there is code that searched for Hebrew characters in the `name` tag.
It was put in place before the convention was changed to use `name:he`.
I prefer that the fix will be in the OSM data, according to the convention.
The bulk update is not run automatically, yet. BTW, I've asked the author to run it again.

**Comment by zstadler** [comment]
This is an issue should be handled by correcting the tagging according to the OSM-IL conventions.
Implementing this has an unjustified performance impact on the tile generation and update processes.

@HarelM 
The JavaScript code for the bulk-edit OSM plug-in is available [on GitHub](https://github.com/SafwatHalaby/osm-bot/blob/master/names.js) under GPL v3. If running it on a regular basis is a priority, you may consider adapting it to work as part of the site.

**Comment by HarelM** [comment]
This is not a priority for me, I think it's important for the map to show correct names and I believe the map server should run this script, but it doesn't really matter who runs it as long as it runs once in a while. Once a month is probably enough too...
