### ISSUE TITLE
Add special mark to Sovev Ramon path

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/VectorMap#26]
In the map have mark to local paths also when they passed on regular paths, to example, Yam Leyam path.
But to Sovev Ramon path haven't special mark when it on regular paths.
Please add this mark.

**Comment by zstadler** [comment]
This is probably a result of removing the `route=hiking` tag in [changeset 74356379](https://www.openstreetmap.org/changeset/74356379).

I've reverted the change. Please check tomorrow's map and close the issue if it was fixed.
