### ISSUE TITLE
Add water_tap

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/VectorMap#36]
The default way to add a tap in the iD editor is now:
man_made=water_tap
with an optional drinking_water=yes
rather than amenity=drinking_water
This comes up when you search for ברז in the editor.
There are just 10 nodes like this rigt now but I expect more to be added.
Please add those to the POI water_tap category.

**Comment by zstadler** [comment]
@valleyofdawn 
Should the schema include all `man_made=water_tap` nodes, or just those with `drinking_water=yes`?

**Comment by valleyofdawn** [comment]
Please include also the ones without drinking_water=yes. The iD editor doesn't include this tag by default and the latest edits tend not to have it.

**Comment by zstadler** [comment]
Done
