### ISSUE TITLE
Merge and generalize trails in lower zoom levels

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/VectorMap#41]
In zoom 12 and above, line widths are equal for all `highway` tags. This allows the grouping for merging and simplification to ignore the `highway` tag.

Hopefully, this will improve the rendering of the trails, and the Israel Trail highlighting in particular.

![image](https://user-images.githubusercontent.com/1304610/86450383-1c539980-bd22-11ea-9f07-354ec3797247.png)

**Comment by valleyofdawn** [comment]
Closed, isn't it?

**Comment by zstadler** [comment]
In addition, the broken corners of the Israel Trail highlighting in higher zoom levels could be fixed using
` "layout": {"line-cap": "round"}`

**Comment by zstadler** [comment]
Done
