### ISSUE TITLE
Add oneway:mtb to the transportation layer in the schema

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/VectorMap#43]
This will be used to indicate the direction of MTB singles without interfering with hiker and vehicle routing.

**Comment by zstadler** [comment]
Done

**Comment by zstadler** [comment]
Looks like the value is not included in the map date.

For example, [here](https://www.openstreetmap.org/way/583463778#map=16/31.3771/34.5999)

**Comment by zstadler** [comment]
The schema included `mtb:oneway` rather than `oneway:mtb`
