### ISSUE TITLE
The color of the path name is unclear

### ISSUE THREAD

**Issue by amiad** [IsraelHikingMap/VectorMap#49]
Names of paths are written in the color of the path defined in the relation.
But if the tag osmc:symbol missed or the path haven't color then the color of name is unclear.

Shvil Hadasa: https://israelhiking.osm.org.il/map/18.32/31.7615/35.1504
![Screenshot_2020-09-15 Israel Hiking Map](https://user-images.githubusercontent.com/402108/93185607-4b38b380-f746-11ea-8285-6f85ceab90d8.png)

I think a clear default color should be added for such cases.

**Comment by zstadler** [comment]
Thank you @amiad!
