### ISSUE TITLE
Missing icons for IHM style

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/VectorMap#5]
### Areas
- [x] Practice Area
- [x] Military
- [x] Intermittent water
- [x] Area A
- [x] Area B
- [x] Forest
- [x] <s>Quarry</s>
- [x] Farmland
- [x] Plantation

### Boundaries
- [x] Nature Reserve boundary
- [x] international border "+"
- [x] Fence "x"
- [x] Cliff

### Roads
- [x] Shields
   - [x] motorway - blue
   - [x] trunk - red
   - [x] primary - green
   - [x] secondary - brown
- [x] <s>Step "|"</s>

**Comment by valleyofdawn** [comment]
Cliffs also

**Comment by valleyofdawn** [comment]
> * [x]  Practice Area
> * [x]  Military
> * [x]  Intermittent water
> * [x]  Area A
> * [x]  Area B
> * [ ]  Forest
> * [ ]  Quarry
> * [ ]  Farmland
> * [x]  Plantation
> 
> ### Boundaries
> * [x]  Nature Reserve boundary
> * [x]  international border "+"
> * [x]  Fence "x"
> 
> ### Roads
> * [x]  Shields
>   
>   * [x]  motorway - blue
>   * [x]  trunk - red
>   * [x]  primary - green
>   * [x]  secondary - brown
> * [ ]  Step "|"

**Comment by valleyofdawn** [comment]
Forest
Quarry
Farmland
Do you need me to add the slightly textured patterns for these or want to use solid fills like in il-MTB?

**Comment by zstadler** [comment]
@valleyofdawn,
A few additional requests:
- According to the [new Israeli roads color scheme](https://he.wikipedia.org/wiki/%D7%9B%D7%91%D7%99%D7%A9%D7%99_%D7%99%D7%A9%D7%A8%D7%90%D7%9C#%D7%A6%D7%91%D7%A2_%D7%94%D7%A9%D7%99%D7%9C%D7%95%D7%98), the color for secondary shield should be black rather than brown.
- At this stage, only the quarry pattern is required for the hiking map. Please use the [original SVG](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/quarry.svg) (CC0 license), if possible.

**Comment by valleyofdawn** [comment]
We have a quarry icon in the current sprite, since we have a problem with high zoom patterns on the app, please see if you can use it as a repeating symbol for the quarry areas. It would also rotate, which is nicer.

**Comment by zstadler** [comment]
I originally wanted a white icon, but we can drop that request.
At this stage, the IHM style is also avoiding large sprite-filled areas such as Forest, Farmland, Plantation, etc.

BTW, "plus_pattern" is too big for the international border, and the IHM style ended-up not using it.

**Comment by valleyofdawn** [comment]
I can remove the halo from the quarry icon so you can play with its color.
Let me know how big the plus-pattern should be (percentage-wise) if you still want it.

**Comment by valleyofdawn** [comment]
Is this resolved @zstadler ?

**Comment by zstadler** [comment]
@valleyofdawn, "Forest" and "Farmland" are not marked as done.

**Comment by valleyofdawn** [comment]
Yes, but you wrote above "At this stage, only the quarry pattern is required for the hiking map" so I'm not sure if you want those two solid, patterned, or using the icons I have used for il-MTB.
