### ISSUE TITLE
תמיכה ב Cycling Track

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#51]
Copied from https://github.com/IsraelHikingMap/Site/issues/1309, reported by @Tsurha 
## Feature

פאמפטרק הרצליה. מסומן היטב ב-OSM כ-Cycling Track. לא מוצג במפת האופניים. אם תוכלו לתמוך. בתודה.
כאן:
https://israelhiking.osm.org.il/map/19.00/32.1732/34.8270

**Comment by zstadler** [comment]
https://www.openstreetmap.org/way/297044812

**Comment by valleyofdawn** [comment]
There are 12 such instances. If @zstadler would like to add the "sport" field to the track class under leisure in the schema I can add those.
If not, I suggest adding a tourism=attraction field to them so they show up in the ilMTB map

**Comment by zstadler** [comment]
@valleyofdawn,
The `sport` field was added to the `landuse` layer.
![image](https://user-images.githubusercontent.com/1304610/122688089-d2a9da80-d222-11eb-8769-135154854047.png)

**Comment by Tsurha** [comment]
Still relevant.  This will be a good incentive to map all the pumptracks in Israel appropriately.  

![image](https://user-images.githubusercontent.com/49042192/205432063-6b58b545-12c5-4cb1-a355-a0c8619a28db.png)

**Comment by zstadler** [comment]
At a deeper look at the above, one can see that the various pitches and playgrounds are barely seen on top on the grass landcover. There is a slightly darker shade of green for outline of pitches.

I'll use this shade of green as the fill color and apply it also for playgrounds and tracks.

![image](https://user-images.githubusercontent.com/1304610/210557804-cfb5eac6-fdc9-4724-95fa-9f6d0b28cfca.png)

**Comment by Tsurha** [comment]
The darker shade looks good. Thanks. 
I think a bicycle icon 🚲 should be presented on top of that.  This will give a meaning to that background like the basketball has a 🏀.  Without it a user can't find pumptracks on the cycling map.

**Comment by zstadler** [comment]
The ball is attached to any playground and pitch, regardless of the sport. It can also be added to tracks.

**Comment by Tsurha** [comment]
Please consider adding a bicycle icon to Cycling Tracks. In a cycling map its really appropriate that pumptracks can stand out.
