### ISSUE TITLE
Remove Latin transcripts

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#56]
לדוגמא תעלה ששמה נווה ימין צפון ומתג'ברשת במפה. 
https://israelhiking.osm.org.il/map/18.00/32.1881/34.9412

![Capture](https://user-images.githubusercontent.com/49042192/95010319-f1cef080-0630-11eb-89c1-39dec942e765.PNG)

**Comment by zstadler** [comment]
אמל"ק - זו תוצאה של תיוג חלקי. בעריכה צריך היה להוסיף את השם גם בשדה
`name:he`

בגלל עירוב השפות בארץ והכלל העולמי שהשם נרשם תמיד בשפה המקומית, כללי המיפוי בישראל מבקשים להשתמש גם בשדה שפה הספציפי. הכללים לתיוג שמות בישראל מוסברים בדך הוויקי של הקהילה בכתובת 
https://wiki.openstreetmap.org/wiki/Israel#Naming

מבחינת המפות שבאתר, ‏אם קיים שדה
`name:he`
אז בוודאות הוא בעברית ולכן הוא מוצג בעדיפות ראשונה

שם בלטינית נמצא בעדיפות השניה להצגה במפות שלנו ומכאן התעתיק המוזר שרואים על התעלה
nwwh נווה
ymym ימין
pwn צפון

תעתיק דומה מופיע עבור שמות בערבית שאין להם חלופה בעברית או באנגלית
<img width="10%" src="https://user-images.githubusercontent.com/1304610/95015729-408f8100-0657-11eb-9cb4-5eca869e05b6.png"/>

אם בעדיפות השניה, במקום השם בלטינית ההינו בוחרים להציג את 
`name`
אז שמות רבים היו מופיעים בערבית, גם אם יש להם שם באנגלית, דבר שהיה מכביד יותר על רוב המשתמשים

נשמח עם בעתיד תוסיף את השדה
`name:he`
לעריכות שתעשה

**Comment by amiad** [comment]
לפי איזה כללים נוצר התעתיק? נראה לי מזמין צרות וסיכוי קטן לתעתיק אוטומטי נכון. 
עדיף להשתמש בשמות לפי הסדר:

1. name:he
2. name (עם בדיקה שמכיל תווים עבריים) 
3. name:en

**Comment by zstadler** [comment]
לצערי, היכולת לבדוק אותיות בעברית אינה ראלית.

**Comment by zstadler** [comment]
Since Arab and other fonts are not available, avoiding the `name:latin` fields would resolve this issue.
Thanks @valleyofdawn for the solution!
