### ISSUE TITLE
Add roads under construction 

### ISSUE THREAD

**Issue by nonZero** [IsraelHikingMap/VectorMap#59]
Construction of roads can take time - sometimes even years.  Open spaces become highways and neighborhoods long time before cars are permitted to use them. 

For example consider [this area near Modiin](https://israelhiking.osm.org.il/map/15.70/31.9066/34.9790):

![image](https://user-images.githubusercontent.com/66484/95674169-0e31d680-0bb7-11eb-93c7-364009e74a45.png)

Instead of hills it is now covered in major and minor roads and a lot of houses under construction.

Previously used hiking/biking trails were cut, and **the new roads under construction are used by cyclists and hikers instead**.

The data is constantly updated in OSM.  Here is an example rendering of the area with roads under construction:

![image](https://user-images.githubusercontent.com/66484/95674091-aaa7a900-0bb6-11eb-80f4-67d7cfd49235.png)

Displaying sites under construction is far more useful for planning and understanding the area.

**Comment by valleyofdawn** [comment]
I'll add those to the bike map asap

**Comment by nonZero** [comment]
Cool. Do you want me to add them to `ilMTB.json` as well?

**Comment by valleyofdawn** [comment]
Please don't

**Comment by valleyofdawn** [comment]
Closed by commit #103
