### ISSUE TITLE
Add support for cycle lanes and tracks via the `cycleway` key

### ISSUE THREAD

**Issue by nonZero** [IsraelHikingMap/VectorMap#61]
According to [the OSM wiki](https://wiki.openstreetmap.org/wiki/Bicycle) cycling lanes and tracks can be mapped using the `cycleway` key.  The default [openmaptiles schema](https://openmaptiles.org/schema/#transportation) does not import them. (See also: https://github.com/openmaptiles/openmaptiles/issues/572 ).

Please add some info regarding the following tags:

```
cycleway=track
cycleway:right=track
cycleway:left=track
cycleway=lane
cycleway:right=lane
cycleway:left=lane
```

In Modiin we will have a lot of `cycleway:right=track` (I am not sure yet if we will have any of all the other options above). For example:

https://www.openstreetmap.org/way/388413831#map=19/31.90866/35.00940

![image](https://user-images.githubusercontent.com/66484/95861073-9a83fb00-0d69-11eb-9eb2-8caff67e771d.png)

cc: @valleyofdawn

**Comment by nonZero** [comment]
Current `cycleway:*=track` in Modiin:

![image](https://user-images.githubusercontent.com/66484/96561040-bd616280-12c7-11eb-8ef8-a1ea42d16ae2.png)


Source: https://overpass-turbo.eu/s/Zdu

**Comment by valleyofdawn** [comment]
Needs to be imported into the schema to be incorporated.
In the meantime you may want to map cycleways separately from the highways.

**Comment by zstadler** [comment]
@valleyofdawn,
Please list the tags you want to add to the `transportation` layer.

**Comment by valleyofdawn** [comment]
Only add a "cycleway" field to transportation classes such as "secondary", "tertiary" etc.
It should contain whatever is there: "right", "left", "both", etc.

**Comment by valleyofdawn** [comment]
Does our routing service support this?

**Comment by zstadler** [comment]
> Does our routing service support this?

I have no idea, but you can try https://graphhopper.com/maps/

**Comment by zstadler** [comment]
It looks to me as if implementing this on the map may cause unnecessary confusion with respect to the routing.

The proposed addition of bicycle lanes to the map would show them on the side/s of the main road. However, OSM only has the center-line position for the main road. Therefore, the planned routes would not show any use of the bicycle lanes. This would be interpreted as if the routing ignores the bicycle lanes. The ability to do extreme zoom-in using the vector tiles will only increase the difference between what the map shows and where the routing is done.

The alternative, which is mention above and used extensively in Tel-Aviv, is to map the bicycle lanes separately and let the routing use them. That way, the routing results and the maps are aligned with each other.

Looking at the benefit of showing the bicycle lanes vs. the potential discrediting of the routing capabilities, I'm inclined to closing this issue without implementing it.

@nonZero, @valleyofdawn, @Tsurha, and @HarelM, what do you think?

**Comment by HarelM** [comment]
I don't have strong feelings either way.
I do think there can be a solution to adding some halo/casing/line to the relevant highways much like we do for the colour tag in the hiking map.
This would mean (and also can be seen in the legend) a different type of highway - one with cycling on the side/both sides.
I don't think the routing is a big factor here much like the fact that if I'm walking on a road I'm probably walking on the sidewalk, but the routing is still dead center...
Adding a highway on the side of a highway feels more like mapping for the renderer, IMHO.

**Comment by nonZero** [comment]
Regarding rendering: For cycling maps the whole road/way could be rendered as "cycling friendly", while ignoring the left/right rendering.

As an editor, in Modiin, and I guess in many other places as well, requiring to maintina a double map (one set of ways for cars, one set of ways for cyclelanes) where this is clearly a cycling track (which is an agreed OSM stadard) does not sound very appealing....

**Comment by zstadler** [comment]
Before:

![image](https://user-images.githubusercontent.com/1304610/210972703-d9644e55-b7ea-4bd0-bd06-15322407f024.png)

After:

![image](https://user-images.githubusercontent.com/1304610/210972654-2eb38ba3-9912-4f01-b420-03c3d637b1aa.png)
