### ISSUE TITLE
Add bicycle repair areas

### ISSUE THREAD

**Issue by nonZero** [IsraelHikingMap/VectorMap#62]
Add rendering to [`amenity=bicycle_repair_station`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_repair_station).

Openstreetmap default rendering:
![image](https://user-images.githubusercontent.com/66484/97069342-50581080-15d8-11eb-84bf-949a70548ff8.png)

Some are installed in Modiin: https://overpass-turbo.eu/s/ZlL

More info: https://www.modiin.muni.il/modiinwebsite/ArticlePage.aspx?PageID=1082_2114

**Comment by valleyofdawn** [comment]
With so few stations in the map it's not worth it to confuse the user with yet another symbol.
We can use the bike-shop symbol and tag it "נקודת תיקון"

**Comment by valleyofdawn** [comment]
This would require adding the stations to the schema. @zstadler 
Could be done but low priority (<10 nodes country-wide currently mapped)

**Comment by zstadler** [comment]
IMO, the [small number of repair station nationwide](https://overpass-turbo.eu/s/18yG) does not justify their addition to the schema.
