### ISSUE TITLE
Missing display of areas 

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#65]
## Bug
לא מוצגים אזורים המסומנים כשטח למשל
* פארק בגין - פארק דרום
* גולף געש
* בית ברל

## What I expect to happen
שיוצג לפחות השם ועדיף גם השטח

## What really happened
לא רואים כלום. לפעמים השטח מוצג בצבע שונה
האזורים קיימים באואסאם

![בגין](https://user-images.githubusercontent.com/49042192/97789925-fdc8b680-1bcc-11eb-96d5-4121096c7c9f.PNG)
![גולף געש](https://user-images.githubusercontent.com/49042192/97789927-00c3a700-1bcd-11eb-9cde-90b094364d9f.PNG)

## What I did that caused the issue - step by step
עברתי על מגוון זומים לבדוק

## My environment
* Operating System and version: בחלונות 10
* Web Browser and version: כרום

**Comment by zstadler** [comment]
הקריאה מתייחסת למפת האופניים

**Comment by Tsurha** [comment]
הקריאה מתייחסת לשתי המפות. 
קבל למשל שבית ברל לא מוצג בטיולים
![בית ברל](https://user-images.githubusercontent.com/49042192/97848404-b3912380-1cf9-11eb-8579-c17172f4e264.PNG)

**Comment by Tsurha** [comment]
הגולף חסר במפת הטיולים
![Golf](https://user-images.githubusercontent.com/49042192/97848577-f3580b00-1cf9-11eb-9acc-1d5ca529f8c2.PNG)

**Comment by zstadler** [comment]
שלשת השטחים שבקריאה מופיעים במפת הטיולים
מפת הטיולים, כשמה כן היא, מיועדת לשרת את צרכי המטייל
כל תוספת של מידע למפה מורידה מיכולת ההתמצאות במידע שכבר קיים בה
לכן, אין לי כוונה להוסיף למפת הטיולים שמות של שטחי
leisure=park
או
amenity=collage

**Comment by Tsurha** [comment]
תודה על ההסבר ולגמרי מובן נושא עומס המידע.
יוצאים מצבים אירוניים שבהם לא יודעים איפה פארק הירקון שזה מידע חשוב למטייל
כן מוצג בריכה האקולוגית או הבלון, שהם בתוך פארק הירקון המשמעותי יותר
כלומר שמות נקודות מוצגות אבל שם של שטח גדול ומשמעותי לא

![איפה פארק הירקון](https://user-images.githubusercontent.com/49042192/97915714-99d3f880-1d5a-11eb-8753-eabc9f53dc2d.PNG)

**Comment by Tsurha** [comment]
הערה: בינתיים הגולף בגעש נסגר והשטח הפך לשדות סתם. אז זו לא דוגמא טובה יותר
אבל שדה התעופה בהרצליה למשל, שהוא שטח סגור, או תע"ש רמת השרון, הם דוגמאות אחרות

**Comment by valleyofdawn** [comment]
![image](https://user-images.githubusercontent.com/689201/122643748-43190480-d11a-11eb-8f08-48b0103123cd.png)
שדה התעופה בהרצליה מופיע בשמו.
אתה יכול לתייג את גבולותיו כ- barrier:fence אם תרצה שיופיע כמגודר.
תע"ש רמת השרון מופיע כשטח מגודר. שזה יותר מאשר במפת גוגל או מפ"י. מתן שם על המפה לאזורים בטחונים זו שאלה חשובה ששווה לדון בה בנפרד.
@zstadler 
האם יש אפשרות טכנית לתייג רק פארקים וקמפוסים גדולים בשמם?

**Comment by zstadler** [comment]
לא מכיר דרך שבה ניתן לדעת בסגנון של מפה הווקטורית מה גודל השטח של פוליגון או לדרוש שטקסט לא יחרוג מגבולות הפוליגון שלו

**Comment by Tsurha** [comment]
<div dir="rtl">
ברגע שיש טקסט עם שם זה פיתרון סביר. 
עכשיו שדה התעופה הרצליה מופיע במפת האופניים רק בזום 13 ואז יש עומס מידע טקסטואלי על העיר עצמה.
אולי זה אחרי תיקון המידע של גבולות העיר הבנויה.
אם ההחלטה של 13 היא בשביל שדות התעופה הגדולים אז מובן. בכל מקרה הייתי מציג את השם גם מזום 14 ומעלה.
בכזו התמקדות כבר לא תהייה בעייה של עומס כפי שרואים בצילום המסך שעשית, גא
