### ISSUE TITLE
In MTB, show Pedestrians Street

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#66]
<div dir="rtl">
highway=pedestrian
מוצג כשביל במפת הטיולים
וצריך להיות גם מוצג במפת האופניים
מבקש להציג ויזואלית בין אם מסומן
bicycle = yes
ובין אם לא.  כשם שכביש 6 מוצג אפילו שברור שאופניים לא אמורים להיכנס עליו

למשל השביל הזה:
https://www.openstreetmap.org/edit#map=18/32.25731/34.89361
שבינתיים עודכן ל
Path
אבל הבאג עדיין באג

![אופניים חסר](https://user-images.githubusercontent.com/49042192/97849311-07e8d300-1cfb-11eb-8c17-9646dbf6a24f.PNG)

**Comment by zstadler** [comment]
בלי קשר לקריאה, נראה שיש במקרה הספציפי הזה טעות בתיוג

על פי הוויקי
highway=pedestrian
הוא תיוג שמתאים למדרחוב

> A highway=pedestrian is a **road** or an area mainly or exclusively for pedestrians

ההדגשה, במקור, על העובדה שמדובר על דרך ולא על שביל

**Comment by Tsurha** [comment]
לגבי המיקום הספציפי של הדוגמא, אולי התיוג תקין? אני פשוט לא בטוח
כיוון שזה לא מדרחוב במובן המקובל. זה שביל סלול עבור הולכי רגל ואופניים
בכל מקרה צריך להיות מוצג במפה
