### ISSUE TITLE
בקשה: להציג באופניים מעבר תחתי כפי שמוצג בטיולים

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#67]
המעברים התחתיים עוזרים מאוד לתכנון מסלולים יצירתיים.
במפת הטיולים הם מודגשים ואילו במפת האופניים חבויים.
אם אפשר להעתיק את שיטת הציור שלהם על המפה, אודה

![biking](https://user-images.githubusercontent.com/49042192/97851325-e76e4800-1cfd-11eb-9701-210f6bcf22ff.PNG)
![Hiking](https://user-images.githubusercontent.com/49042192/97851330-e89f7500-1cfd-11eb-967d-05dbd3d9bd19.PNG)

**Comment by valleyofdawn** [comment]
Added
