### ISSUE TITLE
Consider changing the color of tomb in the hiking map

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#71]
It seems that natural caves and history tomb has the same icon and the same color.
I recently saw that these kind of POI are not showing in POI layer (a bug was opened here: https://github.com/IsraelHikingMap/Site/issues/1379)
When looking into why this is missing I noticed it is simply not part of the mapping of the POIs.
When I thought about how to add it I noticed that all the historic POI are in grey color while this one is black.
I believe it will be a good idea to distinguish it from natural cave simply by changing its color to grey (hex color: 666666) and keeping the current icon.
Let me know what you think.
I'll hold up the implementation of the linked issue above to make sure this is aligned as we agreed in the past about keeping the icon and colors similar between the site and the map.
As a side note, this does not apply to the MTB map simply because this tagging does not have an icon there although I think it should be in both maps.
Relevant location can be found here:
https://israelhiking.osm.org.il/map/19.52/32.6428/35.0702
Screenshot:
![image](https://user-images.githubusercontent.com/3269297/101283657-7e8a5c00-37e4-11eb-8f5a-7af7a3c81476.png)

**Comment by HarelM** [comment]
Seems like there's an issue with using the same icon when it comes to public POI editing as currently there's a mapping of 1 to 1 from icon to OSM tagging.
This will break it...
We might consider using a different icon for tomb to currently solve this until a better mechanism will be implemented in the site...

**Comment by zstadler** [comment]
Please suggest an icon for `historic=tomb`.
What, in your oppinion, should be the representation for `historic=tomb` + `tomb=rock-cut`, such as [this](https://www.openstreetmap.org/node/3961410967)?

**Comment by HarelM** [comment]
I'm looking into fixing the above issue correctly - i.e. so that using the same icon will not pose an issue.
In that case, I think using a grey cave icon can be good enough.
What do you think?
Since historic tomb are currently not available in the POI layer in the site I don't a problem fixing this in the map before hand.
(beside the need to update the sprite files on the server...)

**Comment by HarelM** [comment]
Phone discussion summary:
Burial caves and for that matter historic tomb are to be similar entities much like historical monument and historical memorial.
Closing...
