### ISSUE TITLE
Add bus stops to map

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#72]
The following request is from the conversation in the following issue:
https://github.com/IsraelHikingMap/Site/issues/1389
Motivation - Hikers who want to know how to get to a beginning of a route need to know where there are bus stops in order to be able to plan their route accordingly.

**Comment by zstadler** [comment]
From the original discussion, it looks like the hiker is expected to use a 3rd party service, such as Moovit, to do the bus routing.

In this use-case, the hiker would use the trailhead as the destination and the bus routing service will also provide the walking instructions from the bus stop to the trailhead. This is not very different than using your home address as the starting point and letting the routing service provide the walking instructions to the appropriate bus stop.

**Comment by HarelM** [comment]
To summarize phone conversation, bus stop will clutter the map and are less important than other features that are not in the map too for that reason.
A possible solution to this issue it to create a custom map layer with bus stops.
@Yaniv123 please try and fork the following repository to facilitate for this:
https://github.com/HarelM/IHMMapboxMapExample
Assuming you create a geojson file and upload it to github and create a style for the bus stop you could add it as a custom overlay in the desktop site and mobile apps.
Closing...
