### ISSUE TITLE
Israel hiking app stopped working on my android phone (redme note 4 with android 7. I reloaded the app to no avail.

### ISSUE THREAD

**Issue by elon-bartov** [IsraelHikingMap/VectorMap#73]

**Comment by zstadler** [comment]
<div dir="rtl">
שלום אלון,

אנחנו מצטערים על התקלה שאתה חווה. 

מהמייל ששלחת לנו אני מבין שרכשת מנוי למפות האופליין. 

אנא בדוק שהשלמת את התקנת המפות כפי שמוסבר בתשובה לשאלה "[איך רוכשים מנוי ומתקינים את המפות לשימוש אוף-ליין](https://github.com/IsraelHikingMap/Site/wiki/Israel-Hiking-Maps-FAQ#%D7%90%D7%99%D7%9A-%D7%A8%D7%95%D7%9B%D7%A9%D7%99%D7%9D-%D7%9E%D7%A0%D7%95%D7%99-%D7%95%D7%9E%D7%AA%D7%A7%D7%99%D7%A0%D7%99%D7%9D-%D7%90%D7%AA-%D7%94%D7%9E%D7%A4%D7%95%D7%AA-%D7%9C%D7%A9%D7%99%D7%9E%D7%95%D7%A9-%D7%90%D7%95%D7%A3-%D7%9C%D7%99%D7%99%D7%9F)?" 


קרא בבקשה גם את התשובה לשאלה "[איך משתמשים במפות האופליין שקניתי?](https://github.com/IsraelHikingMap/Site/wiki/Israel-Hiking-Maps-FAQ#%D7%90%D7%99%D7%9A-%D7%9E%D7%A9%D7%AA%D7%9E%D7%A9%D7%99%D7%9D-%D7%91%D7%9E%D7%A4%D7%95%D7%AA-%D7%94%D7%90%D7%95%D7%A4%D7%9C%D7%99%D7%99%D7%9F-%D7%A9%D7%A7%D7%A0%D7%99%D7%AA%D7%99)"

אם ההסברים האלו לא פתרו את הבעיה, אנא העלה לכאן צילום מסך "מפות ושכבות" שלך בזמן שאתה חווה את הבעיה.

</div>

**Comment by elon-bartov** [comment]
זאב בוקר טוב!
אכן כן.  רכשתי מפה אופליין לפני חצי שנה והיישומון עבד איתה עד לאחרונה.
אגב: חסרה כאן התכונה שישנה בלוקוס: שמאפשרת לך להבין עם איזו מפה הוא פועל.
אנסה את הצעתך. ואדווח.  (בגיטהב? )
אלון

בתאריך יום א׳, 13 בדצמ׳ 2020, 19:34, מאת zstadler ‏<notifications@github.com

**Comment by elon-bartov** [comment]
שלום זאב!
אכן,  אחרי שטענתי מחדש את המפות אוף ליין,  הוא חזר לעבוד,  גם עם תקשורת וגם
בלי.
עדיין מציקה היא האיטיות שלו,  במיוחד בהשוואה לעמיתיו כמו 'מפות'  וכמו
לוקוס.
תודה
אלון

בתאריך יום ה׳, 31 בדצמ׳ 2020, 11:00, מאת zstadler ‏<notifications@github.com
