### ISSUE TITLE
Larger Icons in high zoom levels

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#77]
In continue to the concept presented in #15 as a user who zooms in deeply I would like the icon to get larger much like the paths gets larger to intuitively know that I zoomed in deep.
Icons that I currently feel are not getting larger enough are synagog and cistern.
Can be seen here:
https://israelhiking.osm.org.il/poi/Coordinates/32.5876_35.0038
https://israelhiking.osm.org.il/poi/Coordinates/32.5959_35.0046
There are probably others I guess, I haven't fully tested this.
For parking, it feels like it has two sizes which does somewhat creates the required effect when zooming in, but I think it can have another size for even deeper zoom.

**Comment by HarelM** [comment]
Thanks! I haven't seen changes for gates, parking and maybe other icons, is it "by design"?

**Comment by zstadler** [comment]
Gates and other icons already had size increase in higher zoom levels.
For example,
https://github.com/IsraelHikingMap/VectorMap/blob/263cfd1412a991ea2499d279d417a9f3ff02f3a5/Styles/IHM.json#L4204-L4214

**Comment by HarelM** [comment]
Oh, I see, thanks!
