### ISSUE TITLE
Include bikeparks in MTB 

### ISSUE THREAD

**Issue by valleyofdawn** [IsraelHikingMap/VectorMap#78]
I began putting these in the map but ran into trouble.
Bike parks in Israel are tagged in OSM as landuse:recreation_ground, sport:mtb
They are imported into the current schema as POI class:recreation_ground, subclass:recreation_ground
Please change the subclass to indicate MTB, otherwise other recreation grounds (such as a playground in the middle of Hebron) will appear in the MTB map as bike parks.
Also, this is useful for orientation in low zoom levels (was included from level 9 in the old raster map) , but now only appears in level 13 and higher. Please import from 9 up.

**Comment by zstadler** [comment]
Done.
