### ISSUE TITLE
Dark red triangle sprite

### ISSUE THREAD

**Issue by zstadler** [IsraelHikingMap/VectorMap#80]
For decorating the outline of minefields - #32

**Comment by valleyofdawn** [comment]
@zstadler 
Do you want the red line to be part of the icon or separate?

**Comment by zstadler** [comment]
Just the triangle without the line. 

Otherwise, the line could be broken and the density of the triangles would be fixed.

**Comment by valleyofdawn** [comment]
The same red as other features, or similar to official maps?

**Comment by zstadler** [comment]
This is what I have in mind:
![image](https://user-images.githubusercontent.com/1304610/107182073-c005d600-69e4-11eb-8905-6fee6bf269ab.png)

Component | `fill-color` | `fill-opacity` | `fill-outline-color`
---|---|:-:|---
Minefield | `#FF7F00` | `0.5` | `#801119`
Triangle | `#DB1E2A` | `1.0` | `#801119`

The size of the triangles could be smaller In lower zoom levels, or they could be removed.

What do you think?

**Comment by HarelM** [comment]
For me, it feels a bit strong, I might consider using red rectangles without any fill, just the outline...? maybe reduce the opacity of the yellow a bit more... not sure...
In any case, it conveys the message and seems like a good starting point :-)

**Comment by zstadler** [comment]
Please play with it and add a screenshot

**Comment by HarelM** [comment]
Do you have a branch you are working on? Did you use another area to test this? Can you share the style you were using to create this?

**Comment by zstadler** [comment]
I created the screenshot in QGIS, using its red triangle marker and some background color

**Comment by zstadler** [comment]
For comparison
![image](https://user-images.githubusercontent.com/1304610/107254675-33890100-6a40-11eb-9aee-e70da6122967.png)

**Comment by HarelM** [comment]
this is a horrible drawing made in paint online but I hope you can understand the concept (imagine the triangles are all around not just where I had the strength to paint them...):
![image](https://user-images.githubusercontent.com/3269297/107770462-16a34500-6d42-11eb-9f41-afae66bc2d48.png)

**Comment by zstadler** [comment]
Currently, the maps include several "danger" areas: military training areas, minitary bases, Area B, and Area A.
Minefields need to have the strongest visual of them all because they pose an immediate danger to travelers and because they are small and could go unnoticed.

**Comment by zstadler** [comment]
Resolved by 082a693
