### ISSUE TITLE
Add SOS wifi points on the map

### ISSUE THREAD

**Issue by dovgazit** [IsraelHikingMap/VectorMap#82]
## feature
Add SOS wifi point on the map - http://www.soswifi.org

## What I expect to happen

create a Fixed layer or points to display the **"SOS wifi point"** on the map  
see on http://www.soswifi.org 

## What really happened

create a new info point.

## My environment
All environment

## Things I think the developers should know, images, links etc.

**see** all the point in this address API points: http://soswifi.org/getDevicesStatus.php

**Comment by HarelM** [comment]
I'm not entirely sure there's added value in these points...

**Comment by dovgazit** [comment]
למה לא.

נקודות wifi פעילות במקומות שהשידור הסלולרי לא קיים.
נקודות אלה יכולות להציל לחיים.

ד"א שולבו כבר במפות offroad.


היישום כלום כסף, יש קישור למצב פעילות הנקודות.



דב
שבת שלום.







בתאריך יום ו׳, 19 בפבר׳ 2021, 12:19, מאת Harel M ‏<notifications@github.com

**Comment by zstadler** [comment]
<div dir="rtl">

אפשר להכין שכבה חיצונית עבור נקודות הגישה והסטטוס שלהם, בדומה ל[שכבת הגבים](https://www.facebook.com/groups/israelhikingmap/permalink/3559965037391997), ולפרסם גם אותה בקבוצת הפייסבוק וברשימת [המקורות החיצוניים](https://github.com/IsraelHikingMap/Site/wiki/Custom-maps).

אני מקווה שיימצא מי שרוצה ויכול לעשות את זה.
</div>

**Comment by zstadler** [comment]
אנא פתחו קריאה חדשה אם יש רצון ליצור שכבה חיצונית שכזו
