### ISSUE TITLE
Add Bus Station Markers

### ISSUE THREAD

**Issue by Yoav6** [IsraelHikingMap/VectorMap#83]
Suggest adding markers for bus stations. When planning trips it's useful to know the available transportation options in the area, both to arrive at the starting point and to get back from the end point (and also if someone wants to make sure they're always within distance of a bus station).

Currently it's quite cumbersome to check for bus stations. The best way i found is finding a spot through the hiking map, looking it up in google maps and using the "Nearby" feature to find bus stations. But then since google doesn't have hiking trails, i have to locate the spot of the bus station on the hiking map and making it starting/ending spot. Having the stations already in the hiking maps will make the process far easier.

**Comment by HarelM** [comment]
Seems like a duplicate of #72...

**Comment by Yoav6** [comment]
Oops, you're right. Thanks for pointing that out.
