### ISSUE TITLE
Construction parking lot should not be presented

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/VectorMap#89]
Reported by @tsurha:
<div dir="rtl">
מגרש חניה בבניה צריך לא להיות מוצג
מיקום למגרש חניה (חנה וסע) עתידי. נמצא עם construction=yes אבל מוצג

**Comment by zstadler** [comment]
This is a taging mistake. The proper tagging should be `construction:amenity=parking`. If actual work has not started, `proposed:amenity=parking` should be used.

@Tsurha, could you fix it?

Ref: https://wiki.openstreetmap.org/wiki/Key:construction

**Comment by Tsurha** [comment]
@zstadler - To me it looks like its exactly the way you asked for it to be tagged
Check it out - https://www.openstreetmap.org/edit#map=18/32.21322/34.83472
![חניה עתידית](https://user-images.githubusercontent.com/49042192/113496953-8692a800-9507-11eb-8643-341e85c5b61b.GIF)

**Comment by zstadler** [comment]
I've corrected the tagging:

![image](https://user-images.githubusercontent.com/1304610/113500216-d469d900-9524-11eb-829c-dab81af0c569.png)
