### ISSUE TITLE
Display aerialway (רכבל)

### ISSUE THREAD

**Issue by zarmi-a** [IsraelHikingMap/VectorMap#91]
It would very helpful if the map will render the  aerialway tag, both the lines that are usually the cables, and points\areas which are the stations.

the Hermon site is good example:
line (the cable): https://www.openstreetmap.org/way/33840481
area (top station): https://www.openstreetmap.org/way/924830994
point (bottom station): https://www.openstreetmap.org/node/387691301

Preferably the stations should also be searchable (as other tourist attractions are)

**Comment by zstadler** [comment]
@zarmi-a,
For stations to be searchable, please [open an issue](https://github.com/IsraelHikingMap/Site/issues/new/choose) in the Site repository.

**Comment by zstadler** [comment]
The elements are already included in the schema with a `class=aerialway`. 
- Lines are part of the `transportation` layer.
- Stations are part of the `poi` layer.

**Comment by zstadler** [comment]
> 
> 
> @zarmi-a,
> For stations to be searchable, please [open an issue](https://github.com/IsraelHikingMap/Site/issues/new/choose) in the Site repository.

Actually, @zarmi-a, station names already appear in the search results:

![image](https://user-images.githubusercontent.com/1304610/113475646-a54d5c00-947f-11eb-9ed6-143bdfaca18a.png)
