### ISSUE TITLE
Show `man_made=reservoir_covered` on map

### ISSUE THREAD

**Issue by zarmi-a** [IsraelHikingMap/VectorMap#93]
preferably, it should display an icon if it is only a point, and a building with an icon on it if it is an area.

an example can be found here:
https://www.openstreetmap.org/way/924830995

**Comment by zstadler** [comment]
The map is showing water tanks tagged with [`man_made=storage_tank`, `content=water`](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dstorage_tank). This seems like a more accurate tagging for the water storage tanks used in Israel.

Most items in the map legend show their OSM tagging when moving the mouse over them or after a long press in the app. For example:

![2021-04-03 18_10_38-Israel Hiking Map — Mozilla Firefox](https://user-images.githubusercontent.com/1304610/113482673-641d7200-94a8-11eb-91a0-0283c66f8048.png)

In additions, most closed way will show as a building if they have a `building` tag, such as `building=yes`, including water tanks. For example, https://israelhiking.osm.org.il/map/19.00/32.1512/34.8483

**Comment by zarmi-a** [comment]
OK.
So I'll edit the item to use the common tagging
