### ISSUE TITLE
 לא מוצגים השבילים על אזור גשר או הגשר עצמו

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#95]
<div dir="rtl">

במפת האופניים מסומן הגשר הזה שהוא משטח/אזור אבל לא במפת הטיולים.
מאידך שביל האופניים ושביל הולכי הרגל מוצגים במפת הטיולים אבל לא באופניים.
ב OSM יש את כל המידע. המיקום כאן :

למשל כאן https://israelhiking.osm.org.il/map/18.49/32.1609/34.8207

![לא מוצגים השבילים על אזור גשר](https://user-images.githubusercontent.com/49042192/117127268-8c003e00-ada4-11eb-8232-5de46e0717bb.GIF)

**Comment by zstadler** [comment]
<div dir="rtl">
במפת הטיולים שני השבילים שעוברים מעל הכביש מסומנים כגשרים.<br/><br/>

<img width="50%" src="https://user-images.githubusercontent.com/1304610/117189785-4022b880-ade7-11eb-804a-a0fd84d469e4.png">

מפת הטיולים  לא מציגה משטחי גשרים. בין השאר, על מנת שאפשר יהיה לראות בברור את הדרכים שמתחתם.

המשך הטיפול בקריאה זו מועבר למפת האופניים ול @valleyofdawn 
</div>

**Comment by zstadler** [comment]
<div dir="rtl">
@Tsurha, <br/>
 אודה אם בעתיד תפתח קריאות נפרדות לכל מפה
</div>

**Comment by zstadler** [comment]
<div dir="rtl">
לאחר סיור במקום, מיפיתי את הקירות התומכים ותיקנתי את המיפוי של שטח הגשר, שהיה גדול מדי.

ומפת הטיולים נעשתה קצת ברורה יותר
<br/><br/>
<img width="45%" src="https://user-images.githubusercontent.com/1304610/117530844-040a7600-afe8-11eb-9779-8b1bac8aeaf0.png"/>
