### ISSUE TITLE
גשר לא מוצג במפת האופניים

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#96]
<div dir="rtl">
גשר מוצג במפת הטיולים אבל לא מוצג במפת האופניים.

לדוגמא כאן:
https://israelhiking.osm.org.il/map/18.31/32.1651/34.8173

![הגשר עצמו חסר במפת האופניים](https://user-images.githubusercontent.com/49042192/117129981-14cca900-ada8-11eb-8b84-3e9ca38e13d9.GIF)

**Comment by valleyofdawn** [comment]
@Tsurha 
Could you check again?
The bridge appears fine on my MTB maps.
![image](https://user-images.githubusercontent.com/689201/121784616-8bd23a00-cbbd-11eb-8860-27ffa7d17fb1.png)

**Comment by Tsurha** [comment]
It looks good now. Thanks for looking into it.
