### ISSUE TITLE
 לא מוצג במפת האופניים Pedestrian Street

### ISSUE THREAD

**Issue by Tsurha** [IsraelHikingMap/VectorMap#98]
## Bug
למשל במיקום הזה לא רואים את השביל במפת האופניים
https://israelhiking.osm.org.il/map/19.00/32.1939/34.8512

כן רואים את השביל במפת הטיולים
לשמחתי לפחות ניווט אופניים עובר שם סבבה. 

## What I expect to happen
שזה יהיה מוצג

## What really happened
כאילו אין שם שביל

![לא מוצג Pedestrian Street](https://user-images.githubusercontent.com/49042192/120999152-78743880-c791-11eb-885f-633f94be32c2.jpg)

**Comment by HarelM** [comment]
The missing road is the following:
https://www.openstreetmap.org/way/302193119
Relevant tagging:
![image](https://user-images.githubusercontent.com/3269297/121008187-63040c00-c79b-11eb-8146-ac6f8dfd1b8b.png)
The issue is probably related to the fact the the highway is tagged as pedestrian...

**Comment by HarelM** [comment]
@Tsurha thanks for your report!
I see that the `pedestrian` tag is used only in IHM style which easily explains this issue, see search results of this repo here:
https://github.com/IsraelHikingMap/VectorMap/search?q=pedestrian

@valleyofdawn

**Comment by zstadler** [comment]
@Tsurha ,

מה ההבדל בין זה לבין #66 שפתחת לפני 7 חודשים?

**Comment by Tsurha** [comment]
היי הראל וזאב
עכשיו אני רואה שזה באמת אותו באג. לא זכרתי שפתחתי כבר אחד באמת מזמן
זה קשה לפיתרון? 
אני יכול לתייג את הרחוב הספציפי הזה כשביל כללי אבל זה לא מרגיש כמו פיתרון נכון לעניין באופן כללי

**Comment by zstadler** [comment]
אני סוגר את הקריאה הזו כי היא כפולה.


לשאלתך, מאד לא מקובל לשנות את התיוג ב OSM על מנת לשלוט בתצוגה במפה זו או אחרת.

**Comment by Tsurha** [comment]
עניין הלא מקובל לשנות לפי רנדרר ספציפי מובן
כיוון שאנחנו עובדים יחד גם על המידע המיפויי וגם על ההצגה שלו, יש מצב שתצליחו לתקן את הבאג עצמו ואני לא אתפתה לשנות לפי הצורך שיש לי במפת האופניים
?

**Comment by zstadler** [comment]
נשתדל.

**Comment by Tsurha** [comment]
עכשיו עובד מצויין.
תודה!
